import type { Activity, Release } from '../types'

export interface Template {
  id: string
  name: string
  description: string
  icon: string
  releases: Omit<Release, 'id'>[]
  activities: Omit<Activity, 'id' | 'num'>[]
}

export const TEMPLATES: Template[] = [
  {
    id: 'rest-api',
    name: 'REST API Backend',
    description: 'Typical server-side project: auth, CRUD resources, file storage, tests, and deploy.',
    icon: '⚙',
    releases: [{ name: 'v1.0', fte: 2 }],
    activities: [
      // ── Setup ──────────────────────────────────────────────────────────────
      {
        epic: 'Setup',
        act: 'Project scaffolding & CI/CD',
        prof: 'DevOps',
        o: 1,
        ml: 2,
        p: 3,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Setup',
        act: 'Database schema & migrations',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 4,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Setup',
        act: 'API documentation setup',
        prof: 'Backend Dev',
        o: 0.5,
        ml: 1,
        p: 2,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Auth ───────────────────────────────────────────────────────────────
      {
        epic: 'Auth',
        act: 'User registration & login',
        prof: 'Backend Dev',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Auth',
        act: 'Password reset flow',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 3,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Auth',
        act: 'OAuth / social login',
        prof: 'Backend Dev',
        o: 2,
        ml: 3,
        p: 6,
        risk: 1,
        notes: '',
        release: 'v1.0',
      },
      // ── Core API ───────────────────────────────────────────────────────────
      {
        epic: 'Core API',
        act: 'Resource CRUD endpoints',
        prof: 'Backend Dev',
        o: 3,
        ml: 5,
        p: 8,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Core API',
        act: 'Search & filtering',
        prof: 'Backend Dev',
        o: 2,
        ml: 3,
        p: 6,
        risk: 1,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Core API',
        act: 'File upload & storage',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 4,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Core API',
        act: 'Email / push notifications',
        prof: 'Backend Dev',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Testing ────────────────────────────────────────────────────────────
      {
        epic: 'Testing',
        act: 'Unit & integration tests',
        prof: 'QA Engineer',
        o: 3,
        ml: 5,
        p: 8,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Deploy ─────────────────────────────────────────────────────────────
      {
        epic: 'Deploy',
        act: 'Containerisation & cloud deploy',
        prof: 'DevOps',
        o: 1,
        ml: 2,
        p: 4,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Deploy',
        act: 'Monitoring & alerting',
        prof: 'DevOps',
        o: 1,
        ml: 2,
        p: 3,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
    ],
  },

  {
    id: 'mobile-mvp',
    name: 'Mobile App MVP',
    description: 'Cross-platform MVP: UX design, auth screens, core features, API integration, and app store release.',
    icon: '📱',
    releases: [{ name: 'MVP', fte: 2 }],
    activities: [
      // ── Design ─────────────────────────────────────────────────────────────
      {
        epic: 'Design',
        act: 'UX wireframes & prototype',
        prof: 'Designer',
        o: 3,
        ml: 5,
        p: 8,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Design',
        act: 'UI component library',
        prof: 'Designer',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      // ── Auth ───────────────────────────────────────────────────────────────
      {
        epic: 'Auth',
        act: 'Login & signup screens',
        prof: 'Frontend Dev',
        o: 1,
        ml: 2,
        p: 3,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Auth',
        act: 'Social login',
        prof: 'Frontend Dev',
        o: 1,
        ml: 2,
        p: 4,
        risk: 1,
        notes: '',
        release: 'MVP',
      },
      // ── Core ───────────────────────────────────────────────────────────────
      {
        epic: 'Core',
        act: 'Onboarding flow',
        prof: 'Frontend Dev',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Core',
        act: 'Home & navigation structure',
        prof: 'Frontend Dev',
        o: 2,
        ml: 4,
        p: 6,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Core',
        act: 'Main feature screens',
        prof: 'Frontend Dev',
        o: 5,
        ml: 8,
        p: 13,
        risk: 2,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Core',
        act: 'Push notifications',
        prof: 'Frontend Dev',
        o: 1,
        ml: 2,
        p: 4,
        risk: 1,
        notes: '',
        release: 'MVP',
      },
      // ── Integration ────────────────────────────────────────────────────────
      {
        epic: 'Integration',
        act: 'REST API integration layer',
        prof: 'Frontend Dev',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Integration',
        act: 'Offline support & caching',
        prof: 'Frontend Dev',
        o: 2,
        ml: 4,
        p: 7,
        risk: 2,
        notes: '',
        release: 'MVP',
      },
      // ── Release ────────────────────────────────────────────────────────────
      {
        epic: 'Release',
        act: 'QA & device compatibility testing',
        prof: 'QA Engineer',
        o: 3,
        ml: 5,
        p: 8,
        risk: 0,
        notes: '',
        release: 'MVP',
      },
      {
        epic: 'Release',
        act: 'App store submission & review',
        prof: 'PM',
        o: 0.5,
        ml: 1,
        p: 3,
        risk: 1,
        notes: '',
        release: 'MVP',
      },
    ],
  },

  {
    id: 'data-pipeline',
    name: 'Data Pipeline',
    description: 'End-to-end data engineering: ingestion, transformation, storage, serving layer, and observability.',
    icon: '⛁',
    releases: [{ name: 'v1.0', fte: 1 }],
    activities: [
      // ── Ingestion ──────────────────────────────────────────────────────────
      {
        epic: 'Ingestion',
        act: 'Source connectors',
        prof: 'Backend Dev',
        o: 3,
        ml: 5,
        p: 8,
        risk: 1,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Ingestion',
        act: 'Schema validation & contracts',
        prof: 'Backend Dev',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Ingestion',
        act: 'Error handling & dead-letter',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 4,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Transform ──────────────────────────────────────────────────────────
      {
        epic: 'Transform',
        act: 'Business logic & transformations',
        prof: 'Backend Dev',
        o: 4,
        ml: 6,
        p: 10,
        risk: 2,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Transform',
        act: 'Data quality checks',
        prof: 'Backend Dev',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Storage ────────────────────────────────────────────────────────────
      {
        epic: 'Storage',
        act: 'Schema design & migrations',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 4,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Storage',
        act: 'Partitioning & indexing strategy',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 3,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Serving ────────────────────────────────────────────────────────────
      {
        epic: 'Serving',
        act: 'Query API / reporting layer',
        prof: 'Backend Dev',
        o: 2,
        ml: 4,
        p: 6,
        risk: 1,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Serving',
        act: 'Dashboards & visualisations',
        prof: 'Frontend Dev',
        o: 2,
        ml: 3,
        p: 6,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      // ── Ops ────────────────────────────────────────────────────────────────
      {
        epic: 'Ops',
        act: 'Orchestration & scheduling',
        prof: 'DevOps',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Ops',
        act: 'Monitoring & alerting',
        prof: 'DevOps',
        o: 2,
        ml: 3,
        p: 5,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
      {
        epic: 'Ops',
        act: 'Documentation & runbook',
        prof: 'Backend Dev',
        o: 1,
        ml: 2,
        p: 3,
        risk: 0,
        notes: '',
        release: 'v1.0',
      },
    ],
  },
]
