/**
 * refund-ui's half of the label contract.
 *
 * The canonical table is `refund-api/src/requests/document-labels.json`, and
 * refund-api asserts against it in `labels.test.ts`. This file transcribes the
 * SAME values and asserts this package's own sources match them, so a label
 * changed on one side of the boundary fails the other side's suite.
 *
 * Transcribed rather than imported on purpose: refund-api (Bun) and refund-ui
 * (pnpm) are deliberately not npm-linked — CLAUDE.md's ### Git explains that a
 * workspace would break the per-app installs and the Vercel/Railway deploys —
 * and reaching across with a relative import would break this package's build
 * root. Same mechanism `computeMileageAmountCents` already uses for ADR-0025's
 * money vectors.
 *
 * WHY IT MATTERS: the exported PDF is generated by refund-api and read next to
 * this UI. When they disagree, an accountant sees "travel_km" on paper and
 * "Travel — mileage (km)" on screen and cannot tell whether they are looking
 * at the same record.
 */

import { describe, expect, it } from 'vitest'
import { EXPENSE_TYPES } from './expenseTypes'
import { strings } from '../strings'

/** Verbatim from refund-api/src/requests/document-labels.json. */
const CANONICAL = {
  expenseType: {
    travel_highway: 'Travel — highway',
    travel_km: 'Travel — mileage (km)',
    travel_parking: 'Travel — parking',
    travel_train: 'Travel — train',
    travel_other_public_transport: 'Travel — other public transport',
    company_manuals: 'Company manuals',
    stationery: 'Stationery',
    representation_meals: 'Representation — meals',
    representation_gifts: 'Representation — gifts',
    office_material: 'Office material',
    postal: 'Postal',
    telephone: 'Telephone',
  },
  entity: {
    welld_it: 'WellD Italia',
    welld_ch: 'WellD CH',
  },
  requestStatus: {
    draft: 'Draft',
    submitted: 'Awaiting decision',
    approved: 'Approved',
    rejected: 'Rejected',
    paid: 'Paid',
  },
} as const

describe('document label parity with refund-api', () => {
  it('every expense type label matches the canonical table', () => {
    for (const option of EXPENSE_TYPES) {
      expect(option.labelEn).toBe(
        CANONICAL.expenseType[option.id as keyof typeof CANONICAL.expenseType],
      )
    }
  })

  it('the catalogue has exactly the canonical set of types — none added or dropped', () => {
    expect(EXPENSE_TYPES.map((o) => o.id).sort()).toEqual(
      Object.keys(CANONICAL.expenseType).sort(),
    )
  })

  it('entity labels match', () => {
    expect(strings.badges.entity).toMatchObject(CANONICAL.entity)
  })

  it('request status labels match', () => {
    expect(strings.badges.requestStatus).toMatchObject(CANONICAL.requestStatus)
  })
})
