// Ambient module declarations for the suite's federated remotes (T9,
// specs/003-suite-shell/tasks.md; admin/App added in T25,
// specs/004-auth-roles-permissions/tasks.md; notify/App added in T13,
// specs/005-notification-center/tasks.md). Module Federation resolves
// `estimai/App`, `refund/App`, `admin/App` and `notify/App` at runtime via a
// virtual module the host's TypeScript program cannot see, so without these
// declarations `tsc` reports TS2307 ("Cannot find module"). Hand-written
// rather than generated by `@module-federation/vite`'s `dts` option —
// disabled in vite.config.ts, same call made for the retired seed remote
// (T2) and for the same reason: a remote's dev server isn't guaranteed to be
// running when the shell's own build/typecheck runs. Update these by hand if
// a remote's exposed `./App` signature changes.
//
// All four remotes expose a single root component with no props (see
// estimai-ui/src/App.tsx T12, refund-ui/src/App.tsx T15, admin-ui/src/App.tsx
// T13, notify-ui/src/App.tsx T14) — the shell mounts it via RemoteMount (T11)
// inside the `/estimai/*`/`/refund/*`/`/admin/*`/`/notify/*` routes
// (src/router.tsx). `/notify/*`, unlike the other three, is NOT
// app-access-gated (plan.md, specs/005-notification-center) — that's a
// routing/permissions concern in router.tsx, unrelated to this module shape
// declaration.

declare module 'estimai/App' {
  import type { ComponentType } from 'react'

  const App: ComponentType
  export default App
}

declare module 'refund/App' {
  import type { ComponentType } from 'react'

  const App: ComponentType
  export default App
}

declare module 'admin/App' {
  import type { ComponentType } from 'react'

  const App: ComponentType
  export default App
}

declare module 'notify/App' {
  import type { ComponentType } from 'react'

  const App: ComponentType
  export default App
}

// Ambient declarations for the four remotes' `./version` exports (version-
// bump plan §C: umbrella suite version in the footer + per-remote versions
// in the About dialog). Same rationale as the `*/App` declarations above —
// hand-written because `dts` generation stays disabled in vite.config.ts —
// and same shape on all four: a single named `REMOTE_VERSION: string`
// export (see each remote's src/version.ts). Consumed by
// ../hooks/useRemoteVersions.ts via dynamic `import('estimai/version')`
// etc., NOT a static import — see that module's doc for why a remote
// missing this export entirely (i.e. one that predates this change) must
// degrade gracefully rather than being a type error at the call site.

declare module 'estimai/version' {
  export const REMOTE_VERSION: string
}

declare module 'refund/version' {
  export const REMOTE_VERSION: string
}

declare module 'admin/version' {
  export const REMOTE_VERSION: string
}

declare module 'notify/version' {
  export const REMOTE_VERSION: string
}
