// Ambient module declarations for the suite's federated remotes (T9,
// specs/003-suite-shell/tasks.md). Module Federation resolves `estimai/App`
// and `refund/App` at runtime via a virtual module the host's TypeScript
// program cannot see, so without these declarations `tsc` reports TS2307
// ("Cannot find module"). Hand-written rather than generated by
// `@module-federation/vite`'s `dts` option — disabled in vite.config.ts,
// same call made for the retired seed remote (T2) and for the same reason:
// refund-ui (T15) doesn't exist yet, so a dts fetch against its dev server
// would just fail. Update these by hand if a remote's exposed `./App` signature
// changes.
//
// Both remotes expose a single root component with no props (see
// estimai-ui/src/App.tsx, T12) — the shell mounts it via RemoteMount
// (T11) inside the `/estimai/*`/`/refund/*` routes (src/router.tsx).

declare module 'estimai/App' {
  import type { ComponentType } from 'react'

  const App: ComponentType
  export default App
}

declare module 'refund/App' {
  import type { ComponentType } from 'react'

  const App: ComponentType
  export default App
}
