// Ambient module declaration for the `shell/session` federated module (T13,
// specs/003-suite-shell/tasks.md). Module Federation resolves `shell/session`
// at runtime via a virtual module the remote's TypeScript program cannot
// see, so without this declaration `tsc` reports TS2307 ("Cannot find
// module"). Hand-written rather than generated by `@module-federation/vite`'s
// `dts` option — disabled in vite.config.ts for the same reason the shell
// disables it for estimai/refund: a dts fetch against a dev server that may
// not be running would fail noisily. Mirrors shell/src/federation/remotes.d.ts's
// own approach exactly (that file declares `estimai/App` + `refund/App` by
// hand for the same reason, in the other direction).
//
// Shape mirrors shell/src/lib/session.ts's real exports (T4) — update this by
// hand if that module's exported shape changes.

declare module 'shell/session' {
  import type { createAuthClient } from 'better-auth/react'

  type AuthClient = ReturnType<typeof createAuthClient>

  /** Authenticated fetch wrapper — see shell/src/lib/session.ts's doc for the full contract. */
  export const apiFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>

  /** Clears the shared in-memory JWT cache. */
  export const clearJwtCache: () => void

  /** Promise-based session fetch (cookie-based) — the shared better-auth client's `getSession`. */
  export const getSession: AuthClient['getSession']

  /** Reactive session hook — the shared better-auth client's `useSession`. */
  export const useSession: AuthClient['useSession']

  /** Ends the shared session; also clears the shared JWT cache before delegating. */
  export const signOut: (
    ...args: Parameters<AuthClient['signOut']>
  ) => Promise<Awaited<ReturnType<AuthClient['signOut']>>>
}
