// Ambient module declarations for the shell modules notify-ui consumes as a
// remote (T14, specs/005-notification-center/tasks.md). Module Federation
// resolves `shell/session` and `shell/tokens.css` at runtime via a virtual
// module TypeScript's program cannot see, so without these declarations
// `tsc` reports TS2307/TS2306 ("Cannot find module"). Hand-written rather
// than generated by `@module-federation/vite`'s `dts` option — disabled in
// vite.config.ts (see that file's comment): this remote's own build may run
// without a live shell dev server. Mirrors admin-ui/src/federation/remotes.d.ts
// and refund-ui/src/federation/remotes.d.ts exactly. Update these by hand if
// the shell's exposed `./session`/`./tokens.css` shape changes
// (shell/src/lib/session.ts, shell/src/styles/tokens.css) — a later task of
// this feature (T10) extends the shell's exposed surface with the
// notification-specific seam (`raiseNotification`, `useUnreadCount`,
// `resetUnreadCount`, `getNotifyBaseUrl`); this declaration is extended then,
// not here, since T14 is scaffold-only and does not consume those yet.

declare module 'shell/session' {
  // Mirrors shell/src/lib/session.ts's public surface — only the members
  // App.tsx actually consumes (useSession) are typed precisely; the rest
  // are typed loosely since this remote does not call them directly today.
  export interface ShellSessionUser {
    id?: string
    name?: string | null
    email?: string | null
    image?: string | null
  }

  export interface ShellSessionState {
    data: { user?: ShellSessionUser } | null
    isPending?: boolean
    error?: unknown
  }

  export const useSession: () => ShellSessionState
  export const getSession: () => Promise<{ data: { user?: ShellSessionUser } } | null>
  export const apiFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
  /** The auth service base URL (the shell's VITE_AUTH_URL) — remotes build /admin/* + /authz/* URLs against this. */
  export const getAuthBaseUrl: () => string
  export const signOut: (...args: unknown[]) => Promise<unknown>
  export const clearJwtCache: () => void
}

declare module 'shell/tokens.css' {
  // Side-effect-only CSS module (the shared Operai design tokens — fonts,
  // palette CSS custom properties, Tailwind `@theme` block) — no exports.
}
